hl.on("hyprland.start", function()
  hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("$HOME/.config/hypr/scripts/Polkit.sh")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("waybar")
  hl.exec_cmd("qs -c overview")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("$HOME/.config/hypr/scripts/Hyprsunset.sh init")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("$HOME/.config/hypr/scripts/DP2ColumnLayout.py")
  hl.exec_cmd("$HOME/.config/hypr/scripts/WallpaperRestore.sh")
  hl.exec_cmd("[workspace 1 silent] firefox")
  hl.exec_cmd("fastpotify")
  hl.exec_cmd("hyprctl dispatch workspace 1")
  hl.exec_cmd("hyprctl setcursor Adwaita 24")
end)
