hl.on("hyprland.start", function()
  hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
  hl.exec_cmd("$HOME/.config/hypr/scripts/Polkit.sh")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("waybar")
  hl.exec_cmd("qs -c overview")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("$HOME/.config/hypr/scripts/Hyprsunset.sh init")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("$HOME/.config/hypr/scripts/WallpaperDaemon.sh")
  hl.exec_cmd("[workspace 1 silent] firefox")
  hl.exec_cmd("spotify --disable-gpu")
  hl.exec_cmd("hyprctl dispatch workspace 1")
  hl.exec_cmd("hyprctl setcursor Adwaita 24")
end)
