local function shell_quote(value)
  return "'" .. value:gsub("'", "'\"'\"'") .. "'"
end

local function dispatch(name, argument)
  if name == "killactive" then
    return hl.dsp.window.close()
  end
  if name == "workspace" then
    return hl.dsp.focus({ workspace = argument })
  end
  if name == "togglespecialworkspace" then
    return hl.dsp.workspace.toggle_special(argument == "" and "special" or argument)
  end
  if name == "movetoworkspace" then
    local workspace = argument == "special" and "special:special" or argument
    return hl.dsp.window.move({ workspace = workspace })
  end
  if name == "movewindow" and argument == "" then
    return hl.dsp.window.drag()
  end
  if name == "resizewindow" and argument == "" then
    return hl.dsp.window.resize()
  end
  local command = "hyprctl dispatch " .. name
  if argument ~= "" then command = command .. " " .. shell_quote(argument) end
  return hl.dsp.exec_cmd(command)
end

hl.bind("SUPER + D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window"), {description = "app launcher"})
hl.bind("SUPER + B", hl.dsp.exec_cmd("xdg-open \"https://\""), {description = "open default browser"})
hl.bind("SUPER + A", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/OverviewToggle.sh"), {description = "desktop overview"})
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), {description = "Open terminal"})
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"), {description = "file manager"})
hl.bind("SUPER + T", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ThemeChanger.sh"), {description = "Global theme switcher using Wallust"})
hl.bind("SUPER + H", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/KeyHints.sh"), {description = "help / cheat sheet"})
hl.bind("SUPER + ALT + R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Refresh.sh"), {description = "refresh bar and menus"})
hl.bind("SUPER + ALT + E", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/RofiEmoji.sh"), {description = "emoji menu"})
hl.bind("SUPER + S", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/RofiSearch.sh"), {description = "web search"})
hl.bind("SUPER + CTRL + S", hl.dsp.exec_cmd("rofi -show window"), {description = "window switcher"})
hl.bind("SUPER + ALT + O", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ChangeBlur.sh"), {description = "toggle blur"})
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/GameMode.sh"), {description = "toggle game mode"})
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ChangeLayout.sh"), {description = "toggle master/dwindle layout"})
hl.bind("SUPER + ALT + V", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ClipManager.sh"), {description = "clipboard manager"})
hl.bind("SUPER + CTRL + R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/RofiThemeSelector.sh"), {description = "rofi theme selector"})
hl.bind("SUPER + CTRL + SHIFT + R", hl.dsp.exec_cmd("pkill rofi || true && $HOME/.config/hypr/scripts/RofiThemeSelector-modified.sh"), {description = "rofi theme selector (modified)"})
-- Do not route these through `hyprctl dispatch`: in Hyprland's Lua config
-- mode, that CLI subcommand evaluates Lua rather than the legacy dispatcher
-- syntax.  Native dispatchers keep the common Super shortcuts working.
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ action = "toggle" }), {description = "fullscreen"})
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ action = "toggle" }), {description = "fullscreen"})
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ action = "toggle", mode = 1 }), {description = "maximize window"})
hl.bind("SUPER + SPACE", hl.dsp.window.float({ action = "toggle" }), {description = "Float current window"})
hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"), {description = "Float all windows"})
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Dropterminal.sh kitty"), {description = "DropDown terminal"})
hl.bind("SUPER + ALT + mouse_down", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Zoom.sh in 2"), {description = "zoom in"})
hl.bind("SUPER + ALT + mouse_up", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Zoom.sh out 2"), {description = "zoom out"})
hl.bind("SUPER + CTRL + ALT + B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"), {description = "toggle waybar on/off"})
hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/WaybarStyles.sh"), {description = "waybar styles menu"})
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/WaybarLayout.sh"), {description = "waybar layout menu"})
hl.bind("SUPER + N", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Hyprsunset.sh toggle"), {description = "toggle night light"})
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/RofiBeats.sh"), {description = "online music"})
hl.bind("SUPER + W", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/WallpaperSelect.sh"), {description = "select wallpaper"})
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/WallpaperEffects.sh"), {description = "wallpaper effects"})
hl.bind("CTRL + ALT + W", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/WallpaperRandom.sh"), {description = "random wallpaper"})
hl.bind("SUPER + CTRL + O", dispatch("setprop", "active opaque toggle"), {description = "toggle active window opacity"})
hl.bind("SUPER + SHIFT + K", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/KeyBinds.sh"), {description = "search keybinds"})
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Animations.sh"), {description = "animations menu"})
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/ZshChangeTheme.sh"), {description = "change oh-my-zsh theme"})
hl.bind("ALT_L + SHIFT_L", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/KeyboardLayout.sh switch"), {locked = true, non_consuming = true, description = "switch keyboard layout globally"})
hl.bind("SHIFT_L + ALT_L", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Tak0-Per-Window-Switch.sh"), {locked = true, non_consuming = true, description = "switch keyboard layout per-window"})
hl.bind("SUPER + ALT + C", hl.dsp.exec_cmd("$HOME/.config/hypr/UserScripts/RofiCalc.sh"), {description = "calculator"})
hl.bind("SUPER + CTRL + F9", dispatch("movecurrentworkspacetomonitor", "l"), {description = "move workspace to left monitor"})
hl.bind("SUPER + CTRL + F10", dispatch("movecurrentworkspacetomonitor", "r"), {description = "move workspace to right monitor"})
hl.bind("SUPER + CTRL + F11", dispatch("movecurrentworkspacetomonitor", "u"), {description = "move workspace to up monitor"})
hl.bind("SUPER + CTRL + F12", dispatch("movecurrentworkspacetomonitor", "d"), {description = "move workspace to down monitor"})
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("hyprctl dispatch exit 0"), {description = "exit Hyprland"})
hl.bind("SUPER + Q", dispatch("killactive", ""), {description = "close active window"})
hl.bind("SUPER + SHIFT + Q", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/KillActiveProcess.sh"), {description = "Terminate active process"})
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/LockScreen.sh"), {description = "lock screen"})
hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Wlogout.sh"), {description = "powermenu"})
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t -sw"), {description = "notification panel"})
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Kool_Quick_Settings.sh"), {description = "Quick settings menu"})
hl.bind("SUPER + CTRL + D", dispatch("layoutmsg", "removemaster"), {description = "remove master"})
hl.bind("SUPER + I", dispatch("layoutmsg", "addmaster"), {description = "add master"})
hl.bind("SUPER + CTRL + Return", dispatch("layoutmsg", "swapwithmaster"), {description = "swap with master"})
hl.bind("SUPER + SHIFT + I", dispatch("layoutmsg", "togglesplit"), {description = "toggle split (dwindle)"})
hl.bind("SUPER + P", dispatch("pseudo", ""), {description = "toggle pseudo (dwindle)"})
hl.bind("SUPER + M", dispatch("layoutmsg", "splitratio 0.3"), {description = "set split ratio 0.3"})
hl.bind("ALT + tab", dispatch("cyclenext", ""), {description = "cycle next window"})
hl.bind("ALT + tab", dispatch("bringactivetotop", ""), {description = "bring active to top"})
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --inc"), {locked = true, repeating = true, description = "volume up"})
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --dec"), {locked = true, repeating = true, description = "volume down"})
hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --inc-precise"), {locked = true, repeating = true, description = "volume up precise"})
hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --dec-precise"), {locked = true, repeating = true, description = "volume down precise"})
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --toggle-mic"), {locked = true, description = "toggle mic mute"})
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Volume.sh --toggle"), {locked = true, description = "toggle mute"})
hl.bind("XF86Sleep", hl.dsp.exec_cmd("systemctl suspend"), {locked = true, description = "sleep"})
hl.bind("XF86RFKill", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/AirplaneMode.sh"), {locked = true, description = "airplane mode"})
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --pause"), {locked = true, description = "play/pause"})
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --pause"), {locked = true, description = "pause"})
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --pause"), {locked = true, description = "play"})
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --nxt"), {locked = true, description = "next track"})
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --prv"), {locked = true, description = "previous track"})
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/MediaCtrl.sh --stop"), {locked = true, description = "stop"})
hl.bind("SUPER + Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --now"), {description = "screenshot now"})
hl.bind("SUPER + SHIFT + Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --area"), {description = "screenshot (area)"})
hl.bind("SUPER + CTRL + Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --in5"), {description = "screenshot in 5s"})
hl.bind("SUPER + CTRL + SHIFT + Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --in10"), {description = "screenshot in 10s"})
hl.bind("ALT + Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --active"), {description = "screenshot active window"})
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/ScreenShot.sh --swappy"), {description = "screenshot (swappy)"})
hl.bind("SUPER + SHIFT + left", dispatch("resizeactive", "-50 0"), {repeating = true, description = "resize left (-50)"})
hl.bind("SUPER + SHIFT + right", dispatch("resizeactive", "50 0"), {repeating = true, description = "resize right (+50)"})
hl.bind("SUPER + SHIFT + up", dispatch("resizeactive", "0 -50"), {repeating = true, description = "resize up (-50)"})
hl.bind("SUPER + SHIFT + down", dispatch("resizeactive", "0 50"), {repeating = true, description = "resize down (+50)"})
hl.bind("SUPER + CTRL + left", dispatch("movewindow", "l"), {description = "move window left"})
hl.bind("SUPER + CTRL + right", dispatch("movewindow", "r"), {description = "move window right"})
hl.bind("SUPER + CTRL + up", dispatch("movewindow", "u"), {description = "move window up"})
hl.bind("SUPER + CTRL + down", dispatch("movewindow", "d"), {description = "move window down"})
hl.bind("SUPER + ALT + left", dispatch("swapwindow", "l"), {description = "swap window left"})
hl.bind("SUPER + ALT + right", dispatch("swapwindow", "r"), {description = "swap window right"})
hl.bind("SUPER + ALT + up", dispatch("swapwindow", "u"), {description = "swap window up"})
hl.bind("SUPER + ALT + down", dispatch("swapwindow", "d"), {description = "swap window down"})
hl.bind("SUPER + G", dispatch("togglegroup", ""), {description = "toggle group"})
hl.bind("SUPER + Tab", dispatch("changegroupactive", "f"), {description = "Change Group Forward"})
hl.bind("SUPER + CTRL + tab", dispatch("changegroupactive", ""), {description = "change active in group"})
hl.bind("SUPER + SHIFT + Tab", dispatch("changegroupactive", "b"), {description = "Change Group Back"})
hl.bind("SUPER + CTRL + K", dispatch("moveintogroup", "l"), {description = "Move left into group"})
hl.bind("SUPER + CTRL + L", dispatch("moveintogroup", "r"), {description = "Move Right into group"})
hl.bind("SUPER + CTRL + H", dispatch("moveoutofgroup", ""), {description = "Move active out of group"})
hl.bind("SUPER + left", dispatch("movefocus", "l"), {description = "focus left"})
hl.bind("SUPER + right", dispatch("movefocus", "r"), {description = "focus right"})
hl.bind("SUPER + up", dispatch("movefocus", "u"), {description = "focus up"})
hl.bind("SUPER + down", dispatch("movefocus", "d"), {description = "focus down"})
hl.bind("SUPER + tab", dispatch("workspace", "m+1"), {description = "next workspace"})
hl.bind("SUPER + SHIFT + tab", dispatch("workspace", "m-1"), {description = "previous workspace"})
hl.bind("SUPER + SHIFT + U", dispatch("movetoworkspace", "special"), {description = "move to special workspace"})
hl.bind("SUPER + U", dispatch("togglespecialworkspace", ""), {description = "toggle special workspace"})
hl.bind("SUPER + code:10", dispatch("workspace", "1"), {description = "workspace 1"})
hl.bind("SUPER + code:11", dispatch("workspace", "2"), {description = "workspace 2"})
hl.bind("SUPER + code:12", dispatch("workspace", "3"), {description = "workspace 3"})
hl.bind("SUPER + code:13", dispatch("workspace", "4"), {description = "workspace 4"})
hl.bind("SUPER + code:14", dispatch("workspace", "5"), {description = "workspace 5"})
hl.bind("SUPER + code:15", dispatch("workspace", "6"), {description = "workspace 6"})
hl.bind("SUPER + code:16", dispatch("workspace", "7"), {description = "workspace 7"})
hl.bind("SUPER + code:17", dispatch("workspace", "8"), {description = "workspace 8"})
hl.bind("SUPER + code:18", dispatch("workspace", "9"), {description = "workspace 9"})
hl.bind("SUPER + code:19", dispatch("workspace", "10"), {description = "workspace 10"})
hl.bind("SUPER + SHIFT + code:10", dispatch("movetoworkspace", "1"), {description = "move to workspace 1"})
hl.bind("SUPER + SHIFT + code:11", dispatch("movetoworkspace", "2"), {description = "move to workspace 2"})
hl.bind("SUPER + SHIFT + code:12", dispatch("movetoworkspace", "3"), {description = "move to workspace 3"})
hl.bind("SUPER + SHIFT + code:13", dispatch("movetoworkspace", "4"), {description = "move to workspace 4"})
hl.bind("SUPER + SHIFT + code:14", dispatch("movetoworkspace", "5"), {description = "move to workspace 5"})
hl.bind("SUPER + SHIFT + code:15", dispatch("movetoworkspace", "6"), {description = "move to workspace 6"})
hl.bind("SUPER + SHIFT + code:16", dispatch("movetoworkspace", "7"), {description = "move to workspace 7"})
hl.bind("SUPER + SHIFT + code:17", dispatch("movetoworkspace", "8"), {description = "move to workspace 8"})
hl.bind("SUPER + SHIFT + code:18", dispatch("movetoworkspace", "9"), {description = "move to workspace 9"})
hl.bind("SUPER + SHIFT + code:19", dispatch("movetoworkspace", "10"), {description = "move to workspace 10"})
hl.bind("SUPER + SHIFT + bracketleft", dispatch("movetoworkspace", "-1"), {description = "move to previous workspace"})
hl.bind("SUPER + SHIFT + bracketright", dispatch("movetoworkspace", "+1"), {description = "move to next workspace"})
hl.bind("SUPER + CTRL + code:10", dispatch("movetoworkspacesilent", "1"), {description = "move silently to workspace 1"})
hl.bind("SUPER + CTRL + code:11", dispatch("movetoworkspacesilent", "2"), {description = "move silently to workspace 2"})
hl.bind("SUPER + CTRL + code:12", dispatch("movetoworkspacesilent", "3"), {description = "move silently to workspace 3"})
hl.bind("SUPER + CTRL + code:13", dispatch("movetoworkspacesilent", "4"), {description = "move silently to workspace 4"})
hl.bind("SUPER + CTRL + code:14", dispatch("movetoworkspacesilent", "5"), {description = "move silently to workspace 5"})
hl.bind("SUPER + CTRL + code:15", dispatch("movetoworkspacesilent", "6"), {description = "move silently to workspace 6"})
hl.bind("SUPER + CTRL + code:16", dispatch("movetoworkspacesilent", "7"), {description = "move silently to workspace 7"})
hl.bind("SUPER + CTRL + code:17", dispatch("movetoworkspacesilent", "8"), {description = "move silently to workspace 8"})
hl.bind("SUPER + CTRL + code:18", dispatch("movetoworkspacesilent", "9"), {description = "move silently to workspace 9"})
hl.bind("SUPER + CTRL + code:19", dispatch("movetoworkspacesilent", "10"), {description = "move silently to workspace 10"})
hl.bind("SUPER + CTRL + bracketleft", dispatch("movetoworkspacesilent", "-1"), {description = "move silently to previous workspace"})
hl.bind("SUPER + CTRL + bracketright", dispatch("movetoworkspacesilent", "+1"), {description = "move silently to next workspace"})
hl.bind("SUPER + mouse_down", dispatch("workspace", "e+1"), {description = "next workspace"})
hl.bind("SUPER + mouse_up", dispatch("workspace", "e-1"), {description = "previous workspace"})
hl.bind("SUPER + period", dispatch("workspace", "e+1"), {description = "next workspace"})
hl.bind("SUPER + comma", dispatch("workspace", "e-1"), {description = "previous workspace"})
hl.bind("SUPER + mouse:272", dispatch("movewindow", ""), {mouse = true, description = "move window"})
hl.bind("SUPER + mouse:273", dispatch("resizewindow", ""), {mouse = true, description = "resize window"})
hl.bind("XF86KbdBrightnessDown", dispatch("$HOME/.config/hypr/scripts/BrightnessKbd.sh --dec", ""), {repeating = true, description = "exec"})
hl.bind("XF86KbdBrightnessUp", dispatch("$HOME/.config/hypr/scripts/BrightnessKbd.sh --inc", ""), {repeating = true, description = "exec"})
hl.bind("XF86Launch1", dispatch("rog-control-center", ""), {description = "exec"})
hl.bind("XF86Launch3", dispatch("asusctl led-mode -n", ""), {description = "exec"})
hl.bind("XF86Launch4", dispatch("asusctl profile -n", ""), {description = "exec"})
hl.bind("XF86MonBrightnessDown", dispatch("$HOME/.config/hypr/scripts/Brightness.sh --dec", ""), {repeating = true, description = "exec"})
hl.bind("XF86MonBrightnessUp", dispatch("$HOME/.config/hypr/scripts/Brightness.sh --inc", ""), {repeating = true, description = "exec"})
hl.bind("XF86TouchpadToggle", dispatch("$HOME/.config/hypr/scripts/TouchPad.sh", ""), {description = "exec"})
hl.bind("SUPER + F6", dispatch("$HOME/.config/hypr/scripts/ScreenShot.sh --now", ""), {description = "exec"})
hl.bind("SUPER + SHIFT + F6", dispatch("$HOME/.config/hypr/scripts/ScreenShot.sh --area", ""), {description = "exec"})
hl.bind("SUPER + CTRL + F6", dispatch("$HOME/.config/hypr/scripts/ScreenShot.sh --in5", ""), {description = "exec"})
hl.bind("SUPER + ALT + F6", dispatch("$HOME/.config/hypr/scripts/ScreenShot.sh --in10", ""), {description = "exec"})
hl.bind("ALT + F6", dispatch("$HOME/.config/hypr/scripts/ScreenShot.sh --active", ""), {description = "exec"})
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modes drun,window"), {description = "app launcher"})
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/DP2ColumnLayout.py --once"), {description = "choose vertical split for focused pane"})
hl.bind("SUPER + Control_R", dispatch("layoutmsg", "splitratio -0.30"), {description = "set split ratio to 35%"})
hl.bind("SUPER + code:49", dispatch("togglespecialworkspace", "special"), {description = "toggle special workspace"})
hl.bind("SUPER + SHIFT + code:49", dispatch("movetoworkspace", "special"), {description = "move to special workspace"})
hl.unbind("CTRL + ALT + P")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/Wlogout.sh"), {description = "powermenu (wlogout)"})
hl.bind("SUPER + J", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/LayoutAction.sh next"), { description = "layout-aware next" })
hl.bind("SUPER + K", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/LayoutAction.sh prev"), { description = "layout-aware previous" })
hl.bind("SUPER + O", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/LayoutAction.sh split"), { description = "toggle split (dwindle)" })
