# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E9E2E1
background         #141414
cursor             #A39D9C

active_tab_foreground     #141414
active_tab_background     #E9E2E1
inactive_tab_foreground   #E9E2E1
inactive_tab_background   #141414

active_border_color   #E9E2E1
inactive_border_color #141414
bell_border_color     #2F302F

color0      #3B3B3C
color1		#2F302F
color2		#474141
color3		#5F595D
color4		#5F595D
color5		#6F6564
color6		#8F8280
color7		#D6CECC
color8		#96908F
color9		#3E3F3F
color10		#5E5757
color11		#7F777C
color12		#7F777C
color13		#948785
color14		#BFADAA
color15		#D6CECC
