hl.config({ animations = { enabled = true } })
hl.curve("smooth", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("pop", { type = "bezier", points = { {0.34, 1.56}, {0.64, 1} } })
hl.curve("close", { type = "bezier", points = { {0.4, 0}, {1, 1} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.animation({ leaf = "windows", enabled = 1, speed = 4, bezier = "smooth", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = 1, speed = 3, bezier = "pop", style = "popin 88%" })
hl.animation({ leaf = "windowsOut", enabled = 1, speed = 2, bezier = "close", style = "popin 88%" })
hl.animation({ leaf = "windowsMove", enabled = 1, speed = 4, bezier = "smooth", style = "slide" })
hl.animation({ leaf = "border", enabled = 1, speed = 1, bezier = "linear" })
hl.animation({ leaf = "fade", enabled = 1, speed = 3, bezier = "smooth" })
hl.animation({ leaf = "workspaces", enabled = 1, speed = 4, bezier = "smooth", style = "slidefade 12%" })
hl.animation({ leaf = "workspacesIn", enabled = 1, speed = 4, bezier = "smooth", style = "slidefade 12%" })
hl.animation({ leaf = "workspacesOut", enabled = 1, speed = 4, bezier = "smooth", style = "slidefade 12%" })
