hl.config({ animations = { enabled = true } })
hl.curve("fast", { type = "bezier", points = { {0.2, 0}, {0, 1} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.animation({ leaf = "windows", enabled = 1, speed = 2, bezier = "fast", style = "popin 92%" })
hl.animation({ leaf = "windowsIn", enabled = 1, speed = 2, bezier = "fast", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = 1, speed = 2, bezier = "fast", style = "popin 92%" })
hl.animation({ leaf = "windowsMove", enabled = 1, speed = 2, bezier = "fast", style = "slide" })
hl.animation({ leaf = "border", enabled = 1, speed = 1, bezier = "linear" })
hl.animation({ leaf = "fade", enabled = 1, speed = 2, bezier = "fast" })
hl.animation({ leaf = "workspaces", enabled = 1, speed = 2, bezier = "fast", style = "slidefade 8%" })
hl.animation({ leaf = "workspacesIn", enabled = 1, speed = 2, bezier = "fast", style = "slidefade 8%" })
hl.animation({ leaf = "workspacesOut", enabled = 1, speed = 2, bezier = "fast", style = "slidefade 8%" })
