hl.config({ animations = { enabled = true } })
hl.curve("cinematic", { type = "bezier", points = { {0.22, 1}, {0.36, 1} } })
hl.curve("enter", { type = "bezier", points = { {0.18, 1.15}, {0.3, 1} } })
hl.curve("exit", { type = "bezier", points = { {0.55, 0}, {1, 0.45} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.animation({ leaf = "windows", enabled = 1, speed = 5, bezier = "cinematic", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = 1, speed = 4, bezier = "enter", style = "slide top" })
hl.animation({ leaf = "windowsOut", enabled = 1, speed = 3, bezier = "exit", style = "slide bottom" })
hl.animation({ leaf = "windowsMove", enabled = 1, speed = 5, bezier = "cinematic", style = "slide" })
hl.animation({ leaf = "border", enabled = 1, speed = 2, bezier = "linear" })
hl.animation({ leaf = "fade", enabled = 1, speed = 4, bezier = "cinematic" })
hl.animation({ leaf = "workspaces", enabled = 1, speed = 5, bezier = "cinematic", style = "slidefade 20%" })
hl.animation({ leaf = "workspacesIn", enabled = 1, speed = 5, bezier = "cinematic", style = "slidefade 20%" })
hl.animation({ leaf = "workspacesOut", enabled = 1, speed = 5, bezier = "cinematic", style = "slidefade 20%" })
